# Generated by Django 3.2 on 2021-12-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0002_auto_20211209_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeria',
            name='id',
        ),
        migrations.AddField(
            model_name='galeria',
            name='galeria_id',
            field=models.BigAutoField(default='', editable=False, primary_key=True, serialize=False),
        ),
    ]
