# Generated by Django 3.2 on 2021-12-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0003_auto_20211209_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeria',
            name='galeria_id',
        ),
        migrations.AlterField(
            model_name='galeria',
            name='nombre',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
